version: "3.9"

services:
  api:
    build:
      context: ""
      dockerfile: Dockerfile.dev
    image: "localhost:7002/ebb-dev-backend-test_api:${IMAGE_TAG}"
    container_name: "${CONT_NAME}"
    ports:
      - "${PORT}:80"