version: "3.9"

services:
  api:
    build:
      context: ""
      dockerfile: Dockerfile
    image: "localhost:7002/ebb-backend-test_api:${IMAGE_TAG}"
    container_name: "${CONT_NAME}"
    ports:
      - "${PORT}:80"
      - "${HTTPS}:8072"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV}
    volumes:
      - /etc/nginx/ssl/:/etc/nginx/ssl/:ro